# Generated by Django 6.0.6 on 2026-06-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('lic_name', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(max_length=254)),
                ('cc_emails', models.TextField(help_text='Comma separated CC emails')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('bank', models.CharField(max_length=100)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiary', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('reference_no', models.CharField(max_length=100, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('budget_head', models.CharField(max_length=100)),
                ('lic', models.CharField(max_length=100)),
                ('supporting_pending', models.BooleanField(default=False)),
                ('submit_before_date', models.DateField()),
                ('payment_form_received', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
