# Generated by Django 6.0.6 on 2026-06-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmaster',
            old_name='primary_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='approved_date',
            new_name='approve_date',
        ),
        migrations.RemoveField(
            model_name='emailmaster',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='emailmaster',
            name='lic_name',
        ),
        migrations.RemoveField(
            model_name='emailmaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='lic',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='submit_before_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emailmaster',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='supporting',
            field=models.CharField(blank=True, help_text='Jaise: Bills Attached, Reciept, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='budget_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='reference_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='supporting_pending',
            field=models.TextField(blank=True, help_text='Kya baaki hai, yahan likhein', null=True),
        ),
    ]
