# Generated by Django 6.0.6 on 2026-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_tracking', '0002_rename_primary_email_emailmaster_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cc_email',
            field=models.EmailField(blank=True, help_text='CC mein rakhne ke liye email (Optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='to_email',
            field=models.EmailField(blank=True, help_text='Jis person ko reminder bhejna hai', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='supporting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='supporting_pending',
            field=models.TextField(blank=True, null=True),
        ),
    ]
